name: Backend application build and test
on:
  push:
    branches:
      - main

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout pannu
        uses: actions/checkout@v7
      - name: install java 21
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: java irukiya?
        run: java --version
      - name: mvn irukiya?
        run: mvn --version