name: Backend application build and test
on:
  push:
    branches:
      - main
    
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
      - name: going to build
        run: mvn clean install -DskipTests=true
      - name: mvn testing
        run: mvn test
      - name: docker image build
        run: docker build -t buvanaa/springboot-backend:gta .
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



