name: Backend application build and test
on:
  workflow_dispatch:
    
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@v4
      - name: going to build
        run: mvn clean install -DskipTests=true
      - name: testing
        run: mvn test



